# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: k3d-demo
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: pritunl.wuhanstudio.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k3d-demo
                port: 
                  number: 80
